server:
  port: 16061

spring:
  application:
    name: gateway-zuul-demo


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}


zuul:
  routes:
    ribbon-service-demo: /zhq/**


